### ISSUE TITLE
Add New Feature: Ignore URL Patterns

### ISSUE THREAD

**Issue by zjjiang2** [Wei-J-Huang/dlcheck#14]
Hello @Wei-J-Huang, could I work on this Issue on your repository?

**Comment by Wei-J-Huang** [comment]
Sure, go ahead!

**Comment by zjjiang2** [comment]
Here is my forked repo with the feature completed, please check: https://github.com/zjjiang2/dlcheck.git

**Comment by zjjiang2** [comment]
I will contact your from slack privately.
